create extension if not exists "pgcrypto";

do $$
begin
  create type public.user_role as enum ('user', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.driver_status as enum ('available', 'busy', 'offline');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.delivery_status as enum ('pendente', 'em_rota', 'entregue', 'cancelado');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" text not null unique,
  "authUserId" uuid unique references auth.users (id) on delete set null,
  name text,
  email text unique,
  "loginMethod" text,
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  phone text,
  vehicle text,
  status public.driver_status not null default 'offline',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  "clientName" text not null,
  "originAddress" text not null,
  "originLat" text,
  "originLng" text,
  "destinationAddress" text not null,
  "destinationLat" text,
  "destinationLng" text,
  "driverId" bigint references public.drivers (id) on delete set null,
  "createdByUserId" bigint references public.users (id) on delete set null,
  status public.delivery_status not null default 'pendente',
  "scheduledAt" timestamptz,
  notes text,
  distance text,
  "estimatedTime" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists idx_deliveries_status on public.deliveries (status);
create index if not exists idx_deliveries_driver_id on public.deliveries ("driverId");
create index if not exists idx_deliveries_created_by_user_id on public.deliveries ("createdByUserId");
create index if not exists idx_deliveries_scheduled_at on public.deliveries ("scheduledAt");
create index if not exists idx_users_open_id on public.users ("openId");
create index if not exists idx_users_auth_user_id on public.users ("authUserId");
create index if not exists idx_drivers_status on public.drivers (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where u."authUserId" = auth.uid()
      and u.role = 'admin'
  );
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_name text;
begin
  profile_name :=
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      new.email
    );

  insert into public.users (
    "openId",
    "authUserId",
    name,
    email,
    "loginMethod",
    role
  )
  values (
    new.id::text,
    new.id,
    profile_name,
    new.email,
    'supabase',
    'user'
  )
  on conflict ("authUserId")
  do update set
    "openId" = excluded."openId",
    name = coalesce(excluded.name, public.users.name),
    email = coalesce(excluded.email, public.users.email),
    "loginMethod" = coalesce(public.users."loginMethod", excluded."loginMethod"),
    "updatedAt" = now();

  return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_drivers_updated_at on public.drivers;
create trigger trg_drivers_updated_at
before update on public.drivers
for each row execute function public.set_updated_at();

drop trigger if exists trg_deliveries_updated_at on public.deliveries;
create trigger trg_deliveries_updated_at
before update on public.deliveries
for each row execute function public.set_updated_at();

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.users enable row level security;
alter table public.drivers enable row level security;
alter table public.deliveries enable row level security;

drop policy if exists "users_select_own_or_admin" on public.users;
create policy "users_select_own_or_admin"
on public.users
for select
to authenticated
using (
  "authUserId" = auth.uid()
  or public.is_admin()
);

drop policy if exists "users_insert_own_or_admin" on public.users;
create policy "users_insert_own_or_admin"
on public.users
for insert
to authenticated
with check (
  "authUserId" = auth.uid()
  or public.is_admin()
);

drop policy if exists "users_update_own_or_admin" on public.users;
create policy "users_update_own_or_admin"
on public.users
for update
to authenticated
using (
  "authUserId" = auth.uid()
  or public.is_admin()
)
with check (
  "authUserId" = auth.uid()
  or public.is_admin()
);

drop policy if exists "drivers_select_authenticated" on public.drivers;
create policy "drivers_select_authenticated"
on public.drivers
for select
to authenticated
using (true);

drop policy if exists "drivers_admin_write" on public.drivers;
create policy "drivers_admin_write"
on public.drivers
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "deliveries_select_authenticated" on public.deliveries;
create policy "deliveries_select_authenticated"
on public.deliveries
for select
to authenticated
using (true);

drop policy if exists "deliveries_admin_write" on public.deliveries;
create policy "deliveries_admin_write"
on public.deliveries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
