create extension if not exists "pgcrypto";

do $$
begin
  create type public.user_role as enum ('user', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.driver_status as enum ('available', 'busy', 'offline');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.delivery_status as enum ('pendente', 'em_rota', 'entregue', 'cancelado');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" text not null unique,
  "authUserId" uuid unique references auth.users (id) on delete set null,
  name text,
  email text unique,
  "loginMethod" text,
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  phone text,
  vehicle text,
  status public.driver_status not null default 'offline',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  "clientName" text not null,
  "originAddress" text not null,
  "originLat" text,
  "originLng" text,
  "destinationAddress" text not null,
  "destinationLat" text,
  "destinationLng" text,
  "driverId" bigint references public.drivers (id) on delete set null,
  "createdByUserId" bigint references public.users (id) on delete set null,
  status public.delivery_status not null default 'pendente',
  "scheduledAt" timestamptz,
  notes text,
  distance text,
  "estimatedTime" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists deliveries_status_idx on public.deliveries (status);
create index if not exists deliveries_driver_id_idx on public.deliveries ("driverId");
create index if not exists deliveries_scheduled_at_idx on public.deliveries ("scheduledAt");
create index if not exists users_open_id_idx on public.users ("openId");

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists set_drivers_updated_at on public.drivers;
create trigger set_drivers_updated_at
before update on public.drivers
for each row execute function public.set_updated_at();

drop trigger if exists set_deliveries_updated_at on public.deliveries;
create trigger set_deliveries_updated_at
before update on public.deliveries
for each row execute function public.set_updated_at();
